service:
  serviceTypeHeader : service_type
  servicemap:
    -
     servicename: hello
     commonConfigurations:
       methodType : GET/POST/PUT/DELETE
       inputSchemaFile: 
       outputSchemaFile:
       inputValidationRequired : true
       outputValidationRequired : true
       requiredHeaders : [sharenendsa, vasodsdf]
    -
     servicename: hello2
     commonConfigurations:
       methodType : GET/POST/PUT/DELETE
       inputSchemaFile: 
       outputSchemaFile:
       inputValidationRequired : true
       outputValidationRequired : true
       requiredHeaders : []